### ISSUE TITLE
Create classes for patterns state

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#555]
```
class DropModel(Model):
    def __init__(self):
        super()
        self.segments = []
        self.state = {
            'pattern_center': [],
            'pattern_model': [],
            'confidence': 1.5,
            'convolve_max': 200,
            'convolve_min': 200,
            'DROP_HEIGHT': 1,
            'DROP_LENGTH': 1,
            'WINDOW_SIZE': 0,
            'conv_del_min': 54000,
            'conv_del_max': 55000,
        }
    
```

lets rewrite to 

```

class DropModelState:
    def __init(self):
        self.confidence = 1.5
        ....

class DropModel(Model):
    def __init__(self):
        super()
        self.segments = []
        self.state = DropModelState()
    
```

**Comment by rozetko** [comment]
Subtasks:
- [x] Add base class for models' state #574
- [x] Add ModelState children classes #576 
- [ ] Use ModelState classes in models #582
- [ ] Rename UPPERCASE_FIELDS to lowercase_fields in models' state #577
